# -*- coding: utf-8 -*-
"""Task_2_Image_Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJJjq8MRQQO0TiqLRm_w2gy015cLVhFm
"""

!pip install diffusers transformers accelerate

from diffusers import StableDiffusionPipeline

# Model id
model_id = "runwayml/stable-diffusion-v1-5"

# Load pipeline
pipe = StableDiffusionPipeline.from_pretrained(model_id)

# Move to GPU
pipe = pipe.to("cuda")

# ✅ Text prompt for the image
prompt = "A beautiful landscape with mountains and a sunset"

# ✅ Generate image
image = pipe(prompt).images[0]

# ✅ Display the image in the notebook
image.show()

image.save("generated_image.png")

!jupyter nbconvert --ClearMetadataPreprocessor.enabled=True \
  --ClearOutputPreprocessor.enabled=True \
  --to notebook --inplace Task_2_Image_Generation.ipynb